version: '3.8'

services:
  backend:
    image: crisncris0000/crafts_backend:demo
    container_name: backend_c
    ports:
      - "8080:8080"
    volumes:
      - ./crafts-be:/app

  frontend: 
    image: crisncris0000/crafts_frontend:demo
    container_name: frontend_c
    ports:
        - "8081:80"
      
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: CarolsCrafts
    volumes:
      - ./crafts-be/src/main/resources/postgres/script.sql:/docker-entrypoint-initdb.d/script.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
      